on:
  push:
    branches:
      - master
      - workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
      - run: npm ci
      - run: npm run build
